#server.port = 8001
#spring.jpa.hibernate.ddl-auto=update
#
#
#spring.datasource.url=jdbc:mysql://localhost:3306/product_db
#spring.datasource.username=root
#spring.datasource.password=getoffer
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/iorderdb
    username: root
    password: getoffer
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: order_service

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8050/eureka}


